### ISSUE TITLE
[BUG]: solo mode, EQ point deletion and linear phase mode

### ISSUE THREAD

**Issue by yonderehco1197** [ZL-Audio/ZLEqualizer#114] opened 2024-10-06 00:09 UTC
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
- Plugin version & format: 0.4.0 Software (Pre-Release)
- A clear and concise description of what the bug is:

It seems like the solo mode just stopped working. Once pressed, the sound is muted. I have checked this in all filter types and structures, and the problem persists in each of them.

The second problem has to do with the removal of dots. For example, having three points on the graph, selecting the first two points and deleting them, we get the opposite result - only the last point is deleted, while the first two points are still on the graph. Also, if when deleting a group of points, one of them was in the solo mode, then after deleting it, the solo mode area remains on the chart.

I also encountered severe (0 to 100) CPU load spikes in linear phase mode. They are so short-term that they don't even have time to affect the sound, but, unfortunately, they are constant.

- A clear and concise description of what you expected to happen:
```

### Additional information

```markdown
- Operating system (& version if applicable): Windows 10 22H2
- Hardware (CPU & GPU if applicable):
- DAW: Studio One 6.6.0
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment] 2024-10-06 00:44
> It seems like the solo mode just stopped working. Once pressed, the sound is muted. I have checked this in all filter types and structures, and the problem persists in each of them.

I can reproduce this result. I will look into it ASAP. It will be fixed in the formal 0.4.0 version.

> The second problem has to do with the removal of dots. For example, having three points on the graph, selecting the first two points and deleting them, we get the opposite result - only the last point is deleted, while the first two points are still on the graph.

When you select the first two points, do you actually **select** one of them? Is the third point still **selected**?

> Also, if when deleting a group of points, one of them was in the solo mode, then after deleting it, the solo mode area remains on the chart.

May be related to the first one. I will look into it ASAP. It will be fixed in the formal 0.4.0 version.

> I also encountered severe (0 to 100) CPU load spikes in linear phase mode. They are so short-term that they don't even have time to affect the sound, but, unfortunately, they are constant.

It is because I am using the most naive linear phase in this version, which needs to collect all samples with 341 ms period and process it at once. I think a better idea is using partitioned convolution to remove those spikes (but on average a bit slower). I am not sure whether it will be implemented in the formal 0.4.0 version.

**Comment by yonderehco1197** [comment] 2024-10-06 01:06
> When you select the first two points, do you actually select one of them? Is the third point still selected?

Not really :)

Out of three points, the first two are selected, but the third one (which was not selected at all) is deleted. Moreover, the remaining two points are not deleted together, so you have to delete each one individually.

By the way, thank you so much for such a major update! The mixed phase mode is something I've been secretly dreaming of for a long time :) I'll be sure to vote for you in several categories on the KVR site.

**Comment by zsliu98** [comment] 2024-10-06 11:20
The first bug (solo) should get fixed in a186431ce2f3de8529f047c986e1266f1a9f423d.
The second bug (point selection) might get fixed in 02cbc1bc26ef11010d2177bce8785a7fb392e88a and 69a9874f6e67bd46d33e1342bcc7156af982f1a4.
The third bug (linear phase) should be mitigated in 7eb8e7520f537a23f026b656e3e9998b4e11aed0. However, I'd better use a more efficient third-party FFT and partitioned convolution in the future.

I have also updated the installers in the pre-release (again, except AAX).

**Comment by yonderehco1197** [comment] 2024-10-06 11:54
Confirmed, all three bugs have been fixed.

Many thanks!

**Comment by zsliu98** [comment] 2024-10-06 21:16
Thanks for reporting. As I am not sure whether I will use partitioned convolution (and it seems that third-party FFT is hard to use), I am going to close this issue.

**Closed by zsliu98** 2024-10-06 21:16 UTC
Labels: bug

**Comment by yonderehco1197** [comment] 2024-10-07 01:32
I'm afraid to be intrusive, but it seems that a bug has appeared in the [ae94a78](https://github.com/ZL-Audio/ZLEqualizer/commit/ae94a78d4071f6ee1d843a9744cc2db01be2f0ac) version where the analyzer freezes when the zero delay mode is enabled. I did not create a new release.

Thanks!

**Comment by zsliu98** [comment] 2024-10-07 01:41
> I'm afraid to be intrusive, but it seems that a bug has appeared in the [ae94a78](https://github.com/ZL-Audio/ZLEqualizer/commit/ae94a78d4071f6ee1d843a9744cc2db01be2f0ac) version where the analyzer freezes when the zero delay mode is enabled. I did not create a new release.
> 
> Thanks!

Thanks for the report! Yes, I have also noticed that. It is fixed in 3b74ea07a26d0d096f16be674d0fb4bf0fbaca87 and I will update the release soon. The conflict analyzer also has a small problem.

**Comment by zsliu98** [comment] 2024-10-07 02:14
> I'm afraid to be intrusive, but it seems that a bug has appeared in the [ae94a78](https://github.com/ZL-Audio/ZLEqualizer/commit/ae94a78d4071f6ee1d843a9744cc2db01be2f0ac) version where the analyzer freezes when the zero delay mode is enabled. I did not create a new release.
> 
> Thanks!

Sorry for drafting pre-releases too often. I was trying to fix incorrect global bypass behavior. And that fix actually causes this zero-latency bug. Hopefully they are both fixed now.

**Comment by yonderehco1197** [comment] 2024-10-07 03:21
> Sorry for drafting pre-releases too often. 

Oh, don't worry about that :) With this, the main release will be rid of minor bugs and it will allow you to focus on something more global.

The analyzer has been fixed. Thanks again!
