### ISSUE TITLE
[BUG]: FREEZES DAW WITH MORE THAN ONE INSTANCE IN CAKEWALK

### ISSUE THREAD

**Issue by BobGreene47** [ZL-Audio/ZLEqualizer#137] opened 2024-12-16 21:21 UTC
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
- Plugin version & format:     ZL Equalizer.vst3  x86_64-win

- A clear and concise description of what the bug is:     FREEZES CAKEWALK DAW WHEN USING 2 INSTANCES ON SEPARATE TRACKS - HAS HAPPENED A FEW OF TIMES

- A clear and concise description of what you expected to happen:     I thought you could use 2 or more instances on separate tracks.
```

### Additional information

```markdown
- Operating system (& version if applicable):Windows
Name: 	Windows 10 Pro
Version: 	22H2 (19045.4529) 

- Hardware (CPU & GPU if applicable):Number of CPUs: 
Processor: 	1 physical CPU(s) ; 10 physical cores , 20 logical cores
Name: 	Xeon E5-2690 v2 @ 2990 MHz
Clock frequency: 	2990 Mhz
Socket: 	CPU0
Voltage: 	1 Volt
Manufacturer: 	Intel
Model: 	Family 6 Model 14(Extended 62) Stepping 4
Cache(s): 	Code L1 32 KB, 8-way (*10 Cores) Data L1 32 KB, 8-way (*10 Cores) Unified L2 256 KB, 8-way (*10 Cores) Unified L3 25600 KB, None 

Mainboard:
Model 	1589
Manufacturer 	Hewlett-Packard
Serial number 	2UA5060ZGM
On-board devices: 	Onboard LAN
Onboard 1394 

Display:
Name 	NVIDIA Quadro 600
Chipset 	Quadro 600
RAM 	1024 MB 


- DAW:CAKEWALK VERSION: 2024.11 [BUILD 120, 64 BIT]
```

### Relevant log output

```shell
THE DAW FREEZES SO I HAVE TO GO END THE PROCESS IN TASK MANAGER, THEREFORE I HAVE NO LOG OF THE FREEZE INFO.
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by BobGreene47** [comment] 2024-12-16 21:25
I really like the ZL EQ vst3 plugin, but I need to be able to use it on more than one track to find a balance between instruments without it freezing my DAW. I definitely like it better than even FAB FILTER PRO Q, as it is more user friendly in the interface. Thanx for the plugin, and if you could, please figure out why it freezes when using more than one instance in CakeWalk.

**Comment by zsliu98** [comment] 2024-12-16 21:39
Thanks for reporting. Are you using the normal installer? Would you like to try the installer ZL.Equalizer-0.4.5-Windows-Software.exe? How does this work?

BTW, please do not close the issue. If you close it, I would assume that the issue is solved.

**Closed** 2024-12-27 23:03 UTC
Labels: bug, needs response
