### ISSUE TITLE
[BUG]: Vst3 / Not compatible with Cubase 12 (12.7 last version) on Mac os Catalina 10.15.7 

### ISSUE THREAD

**Issue by VeryOldMe** [ZL-Audio/ZLEqualizer#118] opened 2024-10-12 16:36 UTC
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
Hi,
Thank you for your creativity and to keep all thoses plugins free.

ZL Equalizer seem sadly to not running / Not Compatible with Cubase 12 (12.7 last version) on Mac os Catalina 10.15.7

 I try to fix (it could have been this) ZLEqualizer Vst3 with Terminal ... but nothing change.

Very Strange thing : (it say I need 10.14 to run ???)

Thank you for your help
Bonjour de France :)
```

### Additional information

```markdown
Mac Pro with Mac Catalina 10.15.7 / 64Go / SSD (s) / Radeon RX 580 8Go
Cubase 12.0.7 (2024 last version)
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment] 2024-10-12 16:44
Sorry about that. Because I don't have an old macOS machine and GitHub does not provide one, I am not able to support macOS < 13.

Please refer to https://zl-audio.github.io/help/plugin_installation/#macos-installation for more info.

**Comment by zsliu98** [comment] 2024-10-12 16:45
As it is not a bug, I am closing this issue.

**Closed by zsliu98** 2024-10-12 16:45 UTC
Labels: bug
