### ISSUE TITLE
[BUG]: dont't work

### ISSUE THREAD

**Issue by guidocbt** [ZL-Audio/ZLEqualizer#105] opened 2024-09-05 13:25 UTC
### What happened?

```markdown
- Plugin version & format: ZLEqualizer 0.3.5 
- A clear and concise description of what the bug is:
I installed the plugin on and , I rescan the plugins, I find it but it doesn't open it
- A clear and concise description of what you expected to happen:
```

### Additional information

```markdown
- Operating system (& version if applicable): OSX 10.15.7
- Hardware (CPU & GPU if applicable): 2,3 GHz Intel Core i5 dual-core
- DAW: Ableton Live 11.0.2
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment] 2024-09-05 14:00
Duplicate of #103

See more information at https://zl-audio.github.io/help/plugin_installation/#macos-installation

**Closed by zsliu98** 2024-09-05 14:00 UTC
Labels: bug
