### ISSUE TITLE
OpenGL support (for older machines)

### ISSUE THREAD

**Issue by yonderehco1197** [ZL-Audio/ZLEqualizer#35] opened 2024-03-28 01:01 UTC
Hi!
Thank you very much for a great free product!
I was wondering if it's possible to add OpenGL support (or something similar) for machines that aren't very Metal/Direct2D friendly or just aren't the most productive? I've been experiencing some serious freezes and lags on my not-so-new laptop. I don't know what API Frequalizer uses, but its interface is pretty fast and responsive. Perhaps this will help in some way.

**Comment by zsliu98** [comment] 2024-03-28 02:30
Frequalizer has been on my reference list for a long time (see the README.md). I have already gone through the code and I confirm that we both use JUCE native graphic API.
Unfortunately, this plugin has a very complex spectrum, which cannot be rendered smoothly by software render. OpenGL may be capable of doing this stuff. However, using `juce::OpenGLContext` directly does not help, which indicates that I have to write all the shaders myself. Writing such a complex spectrum in OpenGL is too difficult for me.
BTW, the issue you describe may be caused by some other problems, see #31 #33 . Hopefully, I will fix those problems in the next release. Then you may test it again on your machine.

**Comment by zsliu98** [comment] 2024-03-29 10:38
Hi, would you like to try the attachment in #34 ? I have fixed some known issues. What's more, I also decrease the FPS when the dynamic is off. On my laptop, it nearly halves the GPU usage :blush: (I am not sure whether software render will get a similar improvement).

**Comment by yonderehco1197** [comment] 2024-03-29 11:54
Hi, unfortunately I didn't have enough time to test it for a long time, but unequivocally this version is much more responsive. There are still slight freezes when dragging or changing EQ points (non-critical, but still noticeable) or quickly dragging the plugin window. I would like more overall speed and smoothness, but with just one update you've given me almost full use of this.
Thank you so much! :)

**Comment by yonderehco1197** [comment] 2024-03-29 12:19
Hi, unfortunately I only had time for a small test, but definitely this version is much more responsive. There is still some freezes when dragging or changing EQ points or dragging the plugin window (the higher the drag speed, the bigger the freezes), but overall things are noticeably better. I still miss the overall speed and smoothness, but you've made a lot of progress in one update. Thanks! :)

**Comment by zsliu98** [comment] 2024-03-29 12:50
Thanks for the feedback. I would guess that the freezes are caused by the software rendering. Cause 25Hz seems to be the lowest acceptable FPS, I am afraid that I won't be able to get another improvement easily by decreasing the FPS. I will close this issue for now but feel free to re-open it if necessary.

**Closed by zsliu98** 2024-03-29 12:50 UTC
